name: CI

on:
  push:
    branches:
    - master
  pull_request:
    types:
    - opened
    - synchronize
    - reopened

jobs:
  test:
    name: ${{ matrix.os }} ${{ matrix.julia }} ${{ matrix.ruby }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-20.04
        - ubuntu-18.04
        - macos-10.15
        # - windows-latest
        julia:
        - 1.8
        - 1.6
        ruby:
        - "3.1"
        - "3.0"
        - 2.7
        - debug

    steps:
      - uses: actions/checkout@v2

      - uses: julia-actions/setup-julia@v1
        with:
          julia-version: ${{ matrix.julia }}

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - run: julia lib/julia/libjulia/investigator.jl
      - run: ruby -v

      - run: bundle install

      - run: julia -e 'using Pkg; cd("RbCall.jl"); Pkg.develop(PackageSpec(path = pwd()))'

      - run: rake compile

      - run: rake test

      - run: rake build

      - run: gem install pkg/*.gem
